version: 0.2
phases:
  pre_build:
    commands:
      - "echo Logging in to Docker Hub..."
      #- "systemctl status docker"
      - "docker login --username=\"onkar07patil\" --password=\"onkar1@patil\""
  build:
    commands:
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t onkar07patil/pocwork:latest ."
      - "docker tag onkar07patil/pocwork:latest onkar07patil/pocwork:latest"
  post_build:
    commands:
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push onkar07patil/pocwork:latest"
